# Generated by Django 5.2.1 on 2026-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0007_rename_company_type_structuralcustomer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralreminder',
            name='stop_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
