# Generated by Django 5.2.1 on 2026-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0008_structuralreminder_stop_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralreminder',
            name='stop_recurring',
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
    ]
