# Generated by Django 5.2.1 on 2026-01-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0009_remove_structuralreminder_stop_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralreminder',
            name='occurrence_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='structural.structuralreminder'),
        ),
    ]
