# Generated by Django 5.2.1 on 2026-01-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0010_structuralreminder_occurrence_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralreminder',
            name='occurrence_no',
        ),
        migrations.RemoveField(
            model_name='structuralreminder',
            name='recurring_parent',
        ),
        migrations.CreateModel(
            name='StructuralReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_no', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='structural.structuralreminder')),
            ],
        ),
    ]
