# Generated by Django 5.2.1 on 2026-01-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0012_structuralreminderlog_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralnote',
            name='calendar_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structural.structuralcalendaractivity'),
        ),
    ]
