# Generated by Django 5.2.1 on 2026-01-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0013_structuralnote_calendar_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='structuralnotification',
            name='title',
        ),
    ]
