# Generated by Django 5.2.1 on 2026-01-14 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0014_remove_structuralnotification_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralcalendaractivity',
            name='activity_date',
        ),
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='activity',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='sales_person',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='structural_calendar_activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
