# Generated by Django 5.2.1 on 2026-01-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0015_remove_structuralcalendaractivity_activity_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralcalendaractivity',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structural_calendar_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
