# Generated by Django 5.2.1 on 2026-01-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0016_alter_structuralcalendaractivity_sales_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralcalendaractivity',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_calendar_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
