# Generated by Django 5.2.1 on 2026-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0018_alter_structuralcalendaractivity_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
