# Generated by Django 5.2.1 on 2026-01-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0019_structuralcalendaractivity_activity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='related_reminder',
            new_name='related_reminder_id',
        ),
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='structuralcalendaractivity',
            name='activity_date',
        ),
    ]
