# Generated by Django 5.2.1 on 2026-01-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0020_rename_company_structuralcalendaractivity_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='related_reminder_id',
            new_name='related_reminder',
        ),
        migrations.RenameField(
            model_name='structuralcalendaractivity',
            old_name='user_id',
            new_name='user',
        ),
    ]
