# Generated by Django 5.2.1 on 2025-12-31 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architectural', '0002_alter_architecturalcompany_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturalreminder',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='architecturalreminder',
            name='note',
        ),
        migrations.AddField(
            model_name='architecturalcalendaractivity',
            name='related_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='architectural.architecturalreminder'),
        ),
        migrations.AddField(
            model_name='architecturalcalendaractivity',
            name='title',
            field=models.CharField(default='hi initial activity', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architecturalreminder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='architecturalreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architecturalreminder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='architectural.architecturalproject'),
        ),
        migrations.AddField(
            model_name='architecturalreminder',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='architecturalreminder',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='architecturalreminder',
            name='frequency',
            field=models.CharField(choices=[('None', 'None'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Custom', 'Custom')], max_length=20),
        ),
        migrations.CreateModel(
            name='ArchitecturalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Existing', 'Existing'), ('Potential', 'Potential')], max_length=20)),
                ('existing_category', models.CharField(blank=True, choices=[('GC', 'GC'), ('Builder', 'Builder'), ('Architect', 'Architect')], max_length=20, null=True)),
                ('potential_category', models.CharField(blank=True, choices=[('GC', 'GC'), ('Builder', 'Builder'), ('Architect', 'Architect')], max_length=20, null=True)),
                ('lead_status', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Architectural_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='architecturalcalendaractivity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_activities', to='architectural.architecturalcustomer'),
        ),
        migrations.AlterField(
            model_name='architecturalcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='architectural.architecturalcustomer'),
        ),
        migrations.AlterField(
            model_name='architecturalnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='architectural.architecturalcustomer'),
        ),
        migrations.AlterField(
            model_name='architecturalproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='architectural.architecturalcustomer'),
        ),
        migrations.AlterField(
            model_name='architecturalreminder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='architectural.architecturalcustomer'),
        ),
        migrations.CreateModel(
            name='ArchitecturalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_notifications', to='architectural.architecturalcustomer')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecturalnotifications', to='architectural.architecturalreminder')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecturalnotifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ArchitecturalCompany',
        ),
    ]
