# Generated by Django 5.2.1 on 2026-01-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architectural', '0003_remove_architecturalreminder_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalreminder',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='architecturalnotification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='architectural.architecturalcustomer'),
        ),
        migrations.AlterField(
            model_name='architecturalnotification',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='architectural.architecturalreminder'),
        ),
        migrations.AlterField(
            model_name='architecturalnotification',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
